# Generated by Django 5.0.6 on 2024-12-16 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="imagen",
            field=models.FileField(blank=True, null=True, upload_to="opinion"),
        ),
    ]
